In [1]:
import numpy as np
np.set_printoptions(suppress=True)


## Beispiel aus der Vorlesung

### Kirkhoffsches Spannungsgesetz (Beziehung zwischen Potenital und Spannung)

$$e = -Bx$$
wobei: 
* e... Spannungsvektor (gesucht),
* B... Inzidenzmatrix des Netzwerks, die die Geometrie des Netztwerks beschreibt (gegeben),
* x... Potentialvektor (gesucht)


In [2]:
### Inzidenzmatrix B:

B = np.array([
    [-1, 1, 0, 0, 0],
    [0, -1, 1, 0, 0],
    [0, 0, -1, 1, 0],
    [-1, 0, 0, 1, 0],
    [0, 0, 0, -1, 1],
    [0, 1, 0, 0, -1]
])


### Ohmsche Gesetz (Beziehung zwischen Spannung und Stromstärke)

$$y = C(e+b)$$
wobei:
* y... Stromvektor (gesucht),
* C... Leitwerkmatrix als Diagonalmatrix, die die Widerstände beinhaltet (gegeben),
* b... Spannungsquellenvektor (gegeben)

In [3]:
### Leitwerkmatirx als Diagonalmatrix C:

C = np.diag([1, 1, 1, 1, 1, 1])

### Spannungsquelle Matrix b:

b = np.array([[-2], [0], [4], [0], [0], [0]])

### Kirkhoffsches Stromgesetz

$$B^Ty=0$$
wobei:
* B... transponierte Inzidenzmatrix des Netzwerks, die die Geometrie des Netztwerks beschreibt (gegeben),
* y... Stromvektor (gesucht),


In [4]:
BT = B.T

### Lösung: 

$$B^TCB=B^Tbx$$

In [5]:
BtCB = np.dot(np.dot(BT, C), B)

Btb = np.dot(BT, b)

### Potentialvektor x

In [6]:
BtCB_red = BtCB[:-1, :-1]  # Letzte Zeile und Spalte entfernen
Btb_red = Btb[:-1]       # Letztes Element entfernen

# Löse das reduzierte Gleichungssystem
x_reduced = np.linalg.solve(BtCB_red, Btb_red)

# Füge x_5 = 0 zur Lösung hinzu
x = np.append(x_reduced, 0).reshape(-1, 1) 

# Zeige das Ergebnis
print("x:")
print(x)

x:
[[ 1.]
 [-1.]
 [-2.]
 [ 1.]
 [ 0.]]


### Spannungsvektor e


In [7]:
e = np.dot(-B, x)
e = np.round(e)
e[3] = 0
print("e:")
print(e)

e:
[[ 2.]
 [ 1.]
 [-3.]
 [ 0.]
 [ 1.]
 [ 1.]]


### Stromvektor y

In [8]:
y = e + b
print("y:")
print(y)

y:
[[0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]]


## Aufgabe 2

### Matrizen

In [9]:
B = np.array([[-1,  1,  0,  0,  0,  0],
              [0, -1,  1,  0,  0,  0],
              [0,  0, -1,  1,  0,  0],
              [0,  0,  0, -1,  1,  0],
              [0,  0,  0,  0, -1,  1],
              [1,  0,  0,  0,  0, -1],
              [0,  1,  0,  0,  0, -1],
              [0, -1,  0,  1,  0,  0],
              [0,  1,  0,  0, -1,  0]])

BT = B.T

C = diagonal_matrix = np.diag([1, 1, 1, 1, 1, 1, 0.5, 0.5, 0.25])
b = np.array([[0], [0], [-2], [0], [0], [2], [0], [0], [-4]])


### Lösung: 

$$B^TCB=B^TCbx$$

In [10]:
BtCB = np.dot(np.dot(BT, C), B)

Btb = np.dot(BT, b)

### Potentialvektor x

In [11]:
BtCB_red = BtCB[:-1, :-1]  # Letzte Zeile und Spalte entfernen
Btb_red = Btb[:-1]       # Letztes Element entfernen

# Löse das reduzierte Gleichungssystem
x_reduced = np.linalg.solve(BtCB_red, Btb_red)

# Füge x_5 = 0 zur Lösung hinzu
x = np.append(x_reduced, 0).reshape(-1, 1) 

# Zeige das Ergebnis
print("x:")
print(x)

x:
[[ 0.65]
 [-0.7 ]
 [ 0.65]
 [ 0.  ]
 [ 1.7 ]
 [ 0.  ]]


### Spannungsvektor e


In [12]:
e = np.dot(-B, x)
print("e:")
print(e)

e:
[[ 1.35]
 [-1.35]
 [ 0.65]
 [-1.7 ]
 [ 1.7 ]
 [-0.65]
 [ 0.7 ]
 [-0.7 ]
 [ 2.4 ]]


### Stromvektor y

In [13]:
y = e + b
print("y:")
print(y)

y:
[[ 1.35]
 [-1.35]
 [-1.35]
 [-1.7 ]
 [ 1.7 ]
 [ 1.35]
 [ 0.7 ]
 [-0.7 ]
 [-1.6 ]]
